// Copyright 2024, Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/events/cloud/beyondcorp/appconnections/v1/data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1 {

  /// <summary>Holder for reflection information generated from google/events/cloud/beyondcorp/appconnections/v1/data.proto</summary>
  public static partial class DataReflection {

    #region Descriptor
    /// <summary>File descriptor for google/events/cloud/beyondcorp/appconnections/v1/data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cjtnb29nbGUvZXZlbnRzL2Nsb3VkL2JleW9uZGNvcnAvYXBwY29ubmVjdGlv",
            "bnMvdjEvZGF0YS5wcm90bxIwZ29vZ2xlLmV2ZW50cy5jbG91ZC5iZXlvbmRj",
            "b3JwLmFwcGNvbm5lY3Rpb25zLnYxGh9nb29nbGUvcHJvdG9idWYvdGltZXN0",
            "YW1wLnByb3RvIt0ICg1BcHBDb25uZWN0aW9uEgwKBG5hbWUYASABKAkSLwoL",
            "Y3JlYXRlX3RpbWUYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1w",
            "Ei8KC3VwZGF0ZV90aW1lGAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVz",
            "dGFtcBJbCgZsYWJlbHMYBCADKAsySy5nb29nbGUuZXZlbnRzLmNsb3VkLmJl",
            "eW9uZGNvcnAuYXBwY29ubmVjdGlvbnMudjEuQXBwQ29ubmVjdGlvbi5MYWJl",
            "bHNFbnRyeRIUCgxkaXNwbGF5X25hbWUYBSABKAkSCwoDdWlkGAYgASgJElIK",
            "BHR5cGUYByABKA4yRC5nb29nbGUuZXZlbnRzLmNsb3VkLmJleW9uZGNvcnAu",
            "YXBwY29ubmVjdGlvbnMudjEuQXBwQ29ubmVjdGlvbi5UeXBlEnEKFGFwcGxp",
            "Y2F0aW9uX2VuZHBvaW50GAggASgLMlMuZ29vZ2xlLmV2ZW50cy5jbG91ZC5i",
            "ZXlvbmRjb3JwLmFwcGNvbm5lY3Rpb25zLnYxLkFwcENvbm5lY3Rpb24uQXBw",
            "bGljYXRpb25FbmRwb2ludBISCgpjb25uZWN0b3JzGAkgAygJElQKBXN0YXRl",
            "GAogASgOMkUuZ29vZ2xlLmV2ZW50cy5jbG91ZC5iZXlvbmRjb3JwLmFwcGNv",
            "bm5lY3Rpb25zLnYxLkFwcENvbm5lY3Rpb24uU3RhdGUSWAoHZ2F0ZXdheRgL",
            "IAEoCzJHLmdvb2dsZS5ldmVudHMuY2xvdWQuYmV5b25kY29ycC5hcHBjb25u",
            "ZWN0aW9ucy52MS5BcHBDb25uZWN0aW9uLkdhdGV3YXkaMQoTQXBwbGljYXRp",
            "b25FbmRwb2ludBIMCgRob3N0GAEgASgJEgwKBHBvcnQYAiABKAUa4AEKB0dh",
            "dGV3YXkSWgoEdHlwZRgCIAEoDjJMLmdvb2dsZS5ldmVudHMuY2xvdWQuYmV5",
            "b25kY29ycC5hcHBjb25uZWN0aW9ucy52MS5BcHBDb25uZWN0aW9uLkdhdGV3",
            "YXkuVHlwZRILCgN1cmkYAyABKAkSFAoMaW5ncmVzc19wb3J0GAQgASgFEhMK",
            "C2FwcF9nYXRld2F5GAUgASgJEg0KBWw3cHNjGAYgASgJIjIKBFR5cGUSFAoQ",
            "VFlQRV9VTlNQRUNJRklFRBAAEhQKEEdDUF9SRUdJT05BTF9NSUcQARotCgtM",
            "YWJlbHNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIisK",
            "BFR5cGUSFAoQVFlQRV9VTlNQRUNJRklFRBAAEg0KCVRDUF9QUk9YWRABIl8K",
            "BVN0YXRlEhUKEVNUQVRFX1VOU1BFQ0lGSUVEEAASDAoIQ1JFQVRJTkcQARIL",
            "CgdDUkVBVEVEEAISDAoIVVBEQVRJTkcQAxIMCghERUxFVElORxAEEggKBERP",
            "V04QBSJ7ChZBcHBDb25uZWN0aW9uRXZlbnREYXRhElUKB3BheWxvYWQYASAB",
            "KAsyPy5nb29nbGUuZXZlbnRzLmNsb3VkLmJleW9uZGNvcnAuYXBwY29ubmVj",
            "dGlvbnMudjEuQXBwQ29ubmVjdGlvbkgAiAEBQgoKCF9wYXlsb2FkQqcBqgI5",
            "R29vZ2xlLkV2ZW50cy5Qcm90b2J1Zi5DbG91ZC5CZXlvbmRDb3JwLkFwcENv",
            "bm5lY3Rpb25zLlYxygIwR29vZ2xlXEV2ZW50c1xDbG91ZFxCZXlvbmRDb3Jw",
            "XEFwcENvbm5lY3Rpb25zXFYx6gI1R29vZ2xlOjpFdmVudHM6OkNsb3VkOjpC",
            "ZXlvbmRDb3JwOjpBcHBDb25uZWN0aW9uczo6VjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection), global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Parser, new[]{ "Name", "CreateTime", "UpdateTime", "Labels", "DisplayName", "Uid", "Type", "ApplicationEndpoint", "Connectors", "State", "Gateway" }, null, new[]{ typeof(global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Type), typeof(global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.State) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.ApplicationEndpoint), global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.ApplicationEndpoint.Parser, new[]{ "Host", "Port" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway), global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway.Parser, new[]{ "Type", "Uri", "IngressPort", "AppGateway", "L7Psc" }, null, new[]{ typeof(global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway.Types.Type) }, null, null),
            null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnectionEventData), global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnectionEventData.Parser, new[]{ "Payload" }, new[]{ "Payload" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// A BeyondCorp AppConnection resource represents a BeyondCorp protected
  /// AppConnection to a remote application. It creates all the necessary GCP
  /// components needed for creating a BeyondCorp protected AppConnection. Multiple
  /// connectors can be authorised for a single AppConnection.
  /// </summary>
  public sealed partial class AppConnection : pb::IMessage<AppConnection>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AppConnection> _parser = new pb::MessageParser<AppConnection>(() => new AppConnection());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AppConnection> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.DataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AppConnection() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AppConnection(AppConnection other) : this() {
      name_ = other.name_;
      createTime_ = other.createTime_ != null ? other.createTime_.Clone() : null;
      updateTime_ = other.updateTime_ != null ? other.updateTime_.Clone() : null;
      labels_ = other.labels_.Clone();
      displayName_ = other.displayName_;
      uid_ = other.uid_;
      type_ = other.type_;
      applicationEndpoint_ = other.applicationEndpoint_ != null ? other.applicationEndpoint_.Clone() : null;
      connectors_ = other.connectors_.Clone();
      state_ = other.state_;
      gateway_ = other.gateway_ != null ? other.gateway_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AppConnection Clone() {
      return new AppConnection(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// Required. Unique resource name of the AppConnection.
    /// The name is ignored when creating a AppConnection.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "create_time" field.</summary>
    public const int CreateTimeFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createTime_;
    /// <summary>
    /// Output only. Timestamp when the resource was created.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreateTime {
      get { return createTime_; }
      set {
        createTime_ = value;
      }
    }

    /// <summary>Field number for the "update_time" field.</summary>
    public const int UpdateTimeFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp updateTime_;
    /// <summary>
    /// Output only. Timestamp when the resource was last modified.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp UpdateTime {
      get { return updateTime_; }
      set {
        updateTime_ = value;
      }
    }

    /// <summary>Field number for the "labels" field.</summary>
    public const int LabelsFieldNumber = 4;
    private static readonly pbc::MapField<string, string>.Codec _map_labels_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 34);
    private readonly pbc::MapField<string, string> labels_ = new pbc::MapField<string, string>();
    /// <summary>
    /// Optional. Resource labels to represent user provided metadata.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Labels {
      get { return labels_; }
    }

    /// <summary>Field number for the "display_name" field.</summary>
    public const int DisplayNameFieldNumber = 5;
    private string displayName_ = "";
    /// <summary>
    /// Optional. An arbitrary user-provided name for the AppConnection. Cannot
    /// exceed 64 characters.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DisplayName {
      get { return displayName_; }
      set {
        displayName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 6;
    private string uid_ = "";
    /// <summary>
    /// Output only. A unique identifier for the instance generated by the
    /// system.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uid {
      get { return uid_; }
      set {
        uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 7;
    private global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Type type_ = global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Type.Unspecified;
    /// <summary>
    /// Required. The type of network connectivity used by the AppConnection.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "application_endpoint" field.</summary>
    public const int ApplicationEndpointFieldNumber = 8;
    private global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.ApplicationEndpoint applicationEndpoint_;
    /// <summary>
    /// Required. Address of the remote application endpoint for the BeyondCorp
    /// AppConnection.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.ApplicationEndpoint ApplicationEndpoint {
      get { return applicationEndpoint_; }
      set {
        applicationEndpoint_ = value;
      }
    }

    /// <summary>Field number for the "connectors" field.</summary>
    public const int ConnectorsFieldNumber = 9;
    private static readonly pb::FieldCodec<string> _repeated_connectors_codec
        = pb::FieldCodec.ForString(74);
    private readonly pbc::RepeatedField<string> connectors_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Optional. List of [google.cloud.beyondcorp.v1main.Connector.name] that are
    /// authorised to be associated with this AppConnection.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Connectors {
      get { return connectors_; }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 10;
    private global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.State state_ = global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.State.Unspecified;
    /// <summary>
    /// Output only. The current state of the AppConnection.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.State State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "gateway" field.</summary>
    public const int GatewayFieldNumber = 11;
    private global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway gateway_;
    /// <summary>
    /// Optional. Gateway used by the AppConnection.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway Gateway {
      get { return gateway_; }
      set {
        gateway_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AppConnection);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AppConnection other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(CreateTime, other.CreateTime)) return false;
      if (!object.Equals(UpdateTime, other.UpdateTime)) return false;
      if (!Labels.Equals(other.Labels)) return false;
      if (DisplayName != other.DisplayName) return false;
      if (Uid != other.Uid) return false;
      if (Type != other.Type) return false;
      if (!object.Equals(ApplicationEndpoint, other.ApplicationEndpoint)) return false;
      if(!connectors_.Equals(other.connectors_)) return false;
      if (State != other.State) return false;
      if (!object.Equals(Gateway, other.Gateway)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (createTime_ != null) hash ^= CreateTime.GetHashCode();
      if (updateTime_ != null) hash ^= UpdateTime.GetHashCode();
      hash ^= Labels.GetHashCode();
      if (DisplayName.Length != 0) hash ^= DisplayName.GetHashCode();
      if (Uid.Length != 0) hash ^= Uid.GetHashCode();
      if (Type != global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Type.Unspecified) hash ^= Type.GetHashCode();
      if (applicationEndpoint_ != null) hash ^= ApplicationEndpoint.GetHashCode();
      hash ^= connectors_.GetHashCode();
      if (State != global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.State.Unspecified) hash ^= State.GetHashCode();
      if (gateway_ != null) hash ^= Gateway.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (createTime_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CreateTime);
      }
      if (updateTime_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(UpdateTime);
      }
      labels_.WriteTo(output, _map_labels_codec);
      if (DisplayName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DisplayName);
      }
      if (Uid.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Uid);
      }
      if (Type != global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Type.Unspecified) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Type);
      }
      if (applicationEndpoint_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(ApplicationEndpoint);
      }
      connectors_.WriteTo(output, _repeated_connectors_codec);
      if (State != global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.State.Unspecified) {
        output.WriteRawTag(80);
        output.WriteEnum((int) State);
      }
      if (gateway_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Gateway);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (createTime_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CreateTime);
      }
      if (updateTime_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(UpdateTime);
      }
      labels_.WriteTo(ref output, _map_labels_codec);
      if (DisplayName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DisplayName);
      }
      if (Uid.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Uid);
      }
      if (Type != global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Type.Unspecified) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Type);
      }
      if (applicationEndpoint_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(ApplicationEndpoint);
      }
      connectors_.WriteTo(ref output, _repeated_connectors_codec);
      if (State != global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.State.Unspecified) {
        output.WriteRawTag(80);
        output.WriteEnum((int) State);
      }
      if (gateway_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Gateway);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (createTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreateTime);
      }
      if (updateTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateTime);
      }
      size += labels_.CalculateSize(_map_labels_codec);
      if (DisplayName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DisplayName);
      }
      if (Uid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uid);
      }
      if (Type != global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Type.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (applicationEndpoint_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ApplicationEndpoint);
      }
      size += connectors_.CalculateSize(_repeated_connectors_codec);
      if (State != global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.State.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (gateway_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Gateway);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AppConnection other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.createTime_ != null) {
        if (createTime_ == null) {
          CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreateTime.MergeFrom(other.CreateTime);
      }
      if (other.updateTime_ != null) {
        if (updateTime_ == null) {
          UpdateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        UpdateTime.MergeFrom(other.UpdateTime);
      }
      labels_.MergeFrom(other.labels_);
      if (other.DisplayName.Length != 0) {
        DisplayName = other.DisplayName;
      }
      if (other.Uid.Length != 0) {
        Uid = other.Uid;
      }
      if (other.Type != global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Type.Unspecified) {
        Type = other.Type;
      }
      if (other.applicationEndpoint_ != null) {
        if (applicationEndpoint_ == null) {
          ApplicationEndpoint = new global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.ApplicationEndpoint();
        }
        ApplicationEndpoint.MergeFrom(other.ApplicationEndpoint);
      }
      connectors_.Add(other.connectors_);
      if (other.State != global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.State.Unspecified) {
        State = other.State;
      }
      if (other.gateway_ != null) {
        if (gateway_ == null) {
          Gateway = new global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway();
        }
        Gateway.MergeFrom(other.Gateway);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (createTime_ == null) {
              CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreateTime);
            break;
          }
          case 26: {
            if (updateTime_ == null) {
              UpdateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(UpdateTime);
            break;
          }
          case 34: {
            labels_.AddEntriesFrom(input, _map_labels_codec);
            break;
          }
          case 42: {
            DisplayName = input.ReadString();
            break;
          }
          case 50: {
            Uid = input.ReadString();
            break;
          }
          case 56: {
            Type = (global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Type) input.ReadEnum();
            break;
          }
          case 66: {
            if (applicationEndpoint_ == null) {
              ApplicationEndpoint = new global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.ApplicationEndpoint();
            }
            input.ReadMessage(ApplicationEndpoint);
            break;
          }
          case 74: {
            connectors_.AddEntriesFrom(input, _repeated_connectors_codec);
            break;
          }
          case 80: {
            State = (global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.State) input.ReadEnum();
            break;
          }
          case 90: {
            if (gateway_ == null) {
              Gateway = new global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway();
            }
            input.ReadMessage(Gateway);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (createTime_ == null) {
              CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreateTime);
            break;
          }
          case 26: {
            if (updateTime_ == null) {
              UpdateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(UpdateTime);
            break;
          }
          case 34: {
            labels_.AddEntriesFrom(ref input, _map_labels_codec);
            break;
          }
          case 42: {
            DisplayName = input.ReadString();
            break;
          }
          case 50: {
            Uid = input.ReadString();
            break;
          }
          case 56: {
            Type = (global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Type) input.ReadEnum();
            break;
          }
          case 66: {
            if (applicationEndpoint_ == null) {
              ApplicationEndpoint = new global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.ApplicationEndpoint();
            }
            input.ReadMessage(ApplicationEndpoint);
            break;
          }
          case 74: {
            connectors_.AddEntriesFrom(ref input, _repeated_connectors_codec);
            break;
          }
          case 80: {
            State = (global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.State) input.ReadEnum();
            break;
          }
          case 90: {
            if (gateway_ == null) {
              Gateway = new global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway();
            }
            input.ReadMessage(Gateway);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AppConnection message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Enum containing list of all possible network connectivity options
      /// supported by BeyondCorp AppConnection.
      /// </summary>
      public enum Type {
        /// <summary>
        /// Default value. This value is unused.
        /// </summary>
        [pbr::OriginalName("TYPE_UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// TCP Proxy based BeyondCorp AppConnection. API will default to this if
        /// unset.
        /// </summary>
        [pbr::OriginalName("TCP_PROXY")] TcpProxy = 1,
      }

      /// <summary>
      /// Represents the different states of a AppConnection.
      /// </summary>
      public enum State {
        /// <summary>
        /// Default value. This value is unused.
        /// </summary>
        [pbr::OriginalName("STATE_UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// AppConnection is being created.
        /// </summary>
        [pbr::OriginalName("CREATING")] Creating = 1,
        /// <summary>
        /// AppConnection has been created.
        /// </summary>
        [pbr::OriginalName("CREATED")] Created = 2,
        /// <summary>
        /// AppConnection's configuration is being updated.
        /// </summary>
        [pbr::OriginalName("UPDATING")] Updating = 3,
        /// <summary>
        /// AppConnection is being deleted.
        /// </summary>
        [pbr::OriginalName("DELETING")] Deleting = 4,
        /// <summary>
        /// AppConnection is down and may be restored in the future.
        /// This happens when CCFE sends ProjectState = OFF.
        /// </summary>
        [pbr::OriginalName("DOWN")] Down = 5,
      }

      /// <summary>
      /// ApplicationEndpoint represents a remote application endpoint.
      /// </summary>
      public sealed partial class ApplicationEndpoint : pb::IMessage<ApplicationEndpoint>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ApplicationEndpoint> _parser = new pb::MessageParser<ApplicationEndpoint>(() => new ApplicationEndpoint());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ApplicationEndpoint> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ApplicationEndpoint() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ApplicationEndpoint(ApplicationEndpoint other) : this() {
          host_ = other.host_;
          port_ = other.port_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ApplicationEndpoint Clone() {
          return new ApplicationEndpoint(this);
        }

        /// <summary>Field number for the "host" field.</summary>
        public const int HostFieldNumber = 1;
        private string host_ = "";
        /// <summary>
        /// Required. Hostname or IP address of the remote application endpoint.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Host {
          get { return host_; }
          set {
            host_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "port" field.</summary>
        public const int PortFieldNumber = 2;
        private int port_;
        /// <summary>
        /// Required. Port of the remote application endpoint.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Port {
          get { return port_; }
          set {
            port_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ApplicationEndpoint);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ApplicationEndpoint other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Host != other.Host) return false;
          if (Port != other.Port) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Host.Length != 0) hash ^= Host.GetHashCode();
          if (Port != 0) hash ^= Port.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Host.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Host);
          }
          if (Port != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(Port);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Host.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Host);
          }
          if (Port != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(Port);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Host.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Host);
          }
          if (Port != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Port);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ApplicationEndpoint other) {
          if (other == null) {
            return;
          }
          if (other.Host.Length != 0) {
            Host = other.Host;
          }
          if (other.Port != 0) {
            Port = other.Port;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Host = input.ReadString();
                break;
              }
              case 16: {
                Port = input.ReadInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Host = input.ReadString();
                break;
              }
              case 16: {
                Port = input.ReadInt32();
                break;
              }
            }
          }
        }
        #endif

      }

      /// <summary>
      /// Gateway represents a user facing component that serves as an entrance to
      /// enable connectivity.
      /// </summary>
      public sealed partial class Gateway : pb::IMessage<Gateway>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Gateway> _parser = new pb::MessageParser<Gateway>(() => new Gateway());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Gateway> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Gateway() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Gateway(Gateway other) : this() {
          type_ = other.type_;
          uri_ = other.uri_;
          ingressPort_ = other.ingressPort_;
          appGateway_ = other.appGateway_;
          l7Psc_ = other.l7Psc_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Gateway Clone() {
          return new Gateway(this);
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 2;
        private global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway.Types.Type type_ = global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway.Types.Type.Unspecified;
        /// <summary>
        /// Required. The type of hosting used by the gateway.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway.Types.Type Type {
          get { return type_; }
          set {
            type_ = value;
          }
        }

        /// <summary>Field number for the "uri" field.</summary>
        public const int UriFieldNumber = 3;
        private string uri_ = "";
        /// <summary>
        /// Output only. Server-defined URI for this resource.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Uri {
          get { return uri_; }
          set {
            uri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "ingress_port" field.</summary>
        public const int IngressPortFieldNumber = 4;
        private int ingressPort_;
        /// <summary>
        /// Output only. Ingress port reserved on the gateways for this
        /// AppConnection, if not specified or zero, the default port is 19443.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int IngressPort {
          get { return ingressPort_; }
          set {
            ingressPort_ = value;
          }
        }

        /// <summary>Field number for the "app_gateway" field.</summary>
        public const int AppGatewayFieldNumber = 5;
        private string appGateway_ = "";
        /// <summary>
        /// Required. AppGateway name in following format:
        /// `projects/{project_id}/locations/{location_id}/appgateways/{gateway_id}`
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string AppGateway {
          get { return appGateway_; }
          set {
            appGateway_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "l7psc" field.</summary>
        public const int L7PscFieldNumber = 6;
        private string l7Psc_ = "";
        /// <summary>
        /// Output only. L7 private service connection for this resource.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string L7Psc {
          get { return l7Psc_; }
          set {
            l7Psc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Gateway);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Gateway other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Type != other.Type) return false;
          if (Uri != other.Uri) return false;
          if (IngressPort != other.IngressPort) return false;
          if (AppGateway != other.AppGateway) return false;
          if (L7Psc != other.L7Psc) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Type != global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway.Types.Type.Unspecified) hash ^= Type.GetHashCode();
          if (Uri.Length != 0) hash ^= Uri.GetHashCode();
          if (IngressPort != 0) hash ^= IngressPort.GetHashCode();
          if (AppGateway.Length != 0) hash ^= AppGateway.GetHashCode();
          if (L7Psc.Length != 0) hash ^= L7Psc.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Type != global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway.Types.Type.Unspecified) {
            output.WriteRawTag(16);
            output.WriteEnum((int) Type);
          }
          if (Uri.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Uri);
          }
          if (IngressPort != 0) {
            output.WriteRawTag(32);
            output.WriteInt32(IngressPort);
          }
          if (AppGateway.Length != 0) {
            output.WriteRawTag(42);
            output.WriteString(AppGateway);
          }
          if (L7Psc.Length != 0) {
            output.WriteRawTag(50);
            output.WriteString(L7Psc);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Type != global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway.Types.Type.Unspecified) {
            output.WriteRawTag(16);
            output.WriteEnum((int) Type);
          }
          if (Uri.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Uri);
          }
          if (IngressPort != 0) {
            output.WriteRawTag(32);
            output.WriteInt32(IngressPort);
          }
          if (AppGateway.Length != 0) {
            output.WriteRawTag(42);
            output.WriteString(AppGateway);
          }
          if (L7Psc.Length != 0) {
            output.WriteRawTag(50);
            output.WriteString(L7Psc);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Type != global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway.Types.Type.Unspecified) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
          }
          if (Uri.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Uri);
          }
          if (IngressPort != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(IngressPort);
          }
          if (AppGateway.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(AppGateway);
          }
          if (L7Psc.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(L7Psc);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Gateway other) {
          if (other == null) {
            return;
          }
          if (other.Type != global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway.Types.Type.Unspecified) {
            Type = other.Type;
          }
          if (other.Uri.Length != 0) {
            Uri = other.Uri;
          }
          if (other.IngressPort != 0) {
            IngressPort = other.IngressPort;
          }
          if (other.AppGateway.Length != 0) {
            AppGateway = other.AppGateway;
          }
          if (other.L7Psc.Length != 0) {
            L7Psc = other.L7Psc;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 16: {
                Type = (global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway.Types.Type) input.ReadEnum();
                break;
              }
              case 26: {
                Uri = input.ReadString();
                break;
              }
              case 32: {
                IngressPort = input.ReadInt32();
                break;
              }
              case 42: {
                AppGateway = input.ReadString();
                break;
              }
              case 50: {
                L7Psc = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 16: {
                Type = (global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection.Types.Gateway.Types.Type) input.ReadEnum();
                break;
              }
              case 26: {
                Uri = input.ReadString();
                break;
              }
              case 32: {
                IngressPort = input.ReadInt32();
                break;
              }
              case 42: {
                AppGateway = input.ReadString();
                break;
              }
              case 50: {
                L7Psc = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the Gateway message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          /// <summary>
          /// Enum listing possible gateway hosting options.
          /// </summary>
          public enum Type {
            /// <summary>
            /// Default value. This value is unused.
            /// </summary>
            [pbr::OriginalName("TYPE_UNSPECIFIED")] Unspecified = 0,
            /// <summary>
            /// Gateway hosted in a GCP regional managed instance group.
            /// </summary>
            [pbr::OriginalName("GCP_REGIONAL_MIG")] GcpRegionalMig = 1,
          }

        }
        #endregion

      }

    }
    #endregion

  }

  /// <summary>
  /// The data within all AppConnection events.
  /// </summary>
  public sealed partial class AppConnectionEventData : pb::IMessage<AppConnectionEventData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AppConnectionEventData> _parser = new pb::MessageParser<AppConnectionEventData>(() => new AppConnectionEventData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AppConnectionEventData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.DataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AppConnectionEventData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AppConnectionEventData(AppConnectionEventData other) : this() {
      payload_ = other.payload_ != null ? other.payload_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AppConnectionEventData Clone() {
      return new AppConnectionEventData(this);
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 1;
    private global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection payload_;
    /// <summary>
    /// Optional. The AppConnection event payload. Unset for deletion events.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection Payload {
      get { return payload_; }
      set {
        payload_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AppConnectionEventData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AppConnectionEventData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Payload, other.Payload)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (payload_ != null) hash ^= Payload.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (payload_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Payload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (payload_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Payload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (payload_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Payload);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AppConnectionEventData other) {
      if (other == null) {
        return;
      }
      if (other.payload_ != null) {
        if (payload_ == null) {
          Payload = new global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection();
        }
        Payload.MergeFrom(other.Payload);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (payload_ == null) {
              Payload = new global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection();
            }
            input.ReadMessage(Payload);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (payload_ == null) {
              Payload = new global::Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1.AppConnection();
            }
            input.ReadMessage(Payload);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
