// Copyright 2024, Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/events/cloud/beyondcorp/clientconnectorservices/v1/data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1 {

  /// <summary>Holder for reflection information generated from google/events/cloud/beyondcorp/clientconnectorservices/v1/data.proto</summary>
  public static partial class DataReflection {

    #region Descriptor
    /// <summary>File descriptor for google/events/cloud/beyondcorp/clientconnectorservices/v1/data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkRnb29nbGUvZXZlbnRzL2Nsb3VkL2JleW9uZGNvcnAvY2xpZW50Y29ubmVj",
            "dG9yc2VydmljZXMvdjEvZGF0YS5wcm90bxI5Z29vZ2xlLmV2ZW50cy5jbG91",
            "ZC5iZXlvbmRjb3JwLmNsaWVudGNvbm5lY3RvcnNlcnZpY2VzLnYxGh9nb29n",
            "bGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvIrkKChZDbGllbnRDb25uZWN0",
            "b3JTZXJ2aWNlEgwKBG5hbWUYASABKAkSLwoLY3JlYXRlX3RpbWUYAiABKAsy",
            "Gi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi8KC3VwZGF0ZV90aW1lGAMg",
            "ASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIUCgxkaXNwbGF5X25h",
            "bWUYBCABKAkSagoHaW5ncmVzcxgGIAEoCzJZLmdvb2dsZS5ldmVudHMuY2xv",
            "dWQuYmV5b25kY29ycC5jbGllbnRjb25uZWN0b3JzZXJ2aWNlcy52MS5DbGll",
            "bnRDb25uZWN0b3JTZXJ2aWNlLkluZ3Jlc3MSaAoGZWdyZXNzGAcgASgLMlgu",
            "Z29vZ2xlLmV2ZW50cy5jbG91ZC5iZXlvbmRjb3JwLmNsaWVudGNvbm5lY3Rv",
            "cnNlcnZpY2VzLnYxLkNsaWVudENvbm5lY3RvclNlcnZpY2UuRWdyZXNzEmYK",
            "BXN0YXRlGAggASgOMlcuZ29vZ2xlLmV2ZW50cy5jbG91ZC5iZXlvbmRjb3Jw",
            "LmNsaWVudGNvbm5lY3RvcnNlcnZpY2VzLnYxLkNsaWVudENvbm5lY3RvclNl",
            "cnZpY2UuU3RhdGUaswQKB0luZ3Jlc3MScgoGY29uZmlnGAEgASgLMmAuZ29v",
            "Z2xlLmV2ZW50cy5jbG91ZC5iZXlvbmRjb3JwLmNsaWVudGNvbm5lY3RvcnNl",
            "cnZpY2VzLnYxLkNsaWVudENvbm5lY3RvclNlcnZpY2UuSW5ncmVzcy5Db25m",
            "aWdIABqhAwoGQ29uZmlnEo4BChJ0cmFuc3BvcnRfcHJvdG9jb2wYASABKA4y",
            "ci5nb29nbGUuZXZlbnRzLmNsb3VkLmJleW9uZGNvcnAuY2xpZW50Y29ubmVj",
            "dG9yc2VydmljZXMudjEuQ2xpZW50Q29ubmVjdG9yU2VydmljZS5JbmdyZXNz",
            "LkNvbmZpZy5UcmFuc3BvcnRQcm90b2NvbBKNAQoSZGVzdGluYXRpb25fcm91",
            "dGVzGAIgAygLMnEuZ29vZ2xlLmV2ZW50cy5jbG91ZC5iZXlvbmRjb3JwLmNs",
            "aWVudGNvbm5lY3RvcnNlcnZpY2VzLnYxLkNsaWVudENvbm5lY3RvclNlcnZp",
            "Y2UuSW5ncmVzcy5Db25maWcuRGVzdGluYXRpb25Sb3V0ZRo0ChBEZXN0aW5h",
            "dGlvblJvdXRlEg8KB2FkZHJlc3MYASABKAkSDwoHbmV0bWFzaxgCIAEoCSJA",
            "ChFUcmFuc3BvcnRQcm90b2NvbBIiCh5UUkFOU1BPUlRfUFJPVE9DT0xfVU5T",
            "UEVDSUZJRUQQABIHCgNUQ1AQAUIQCg5pbmdyZXNzX2NvbmZpZxq4AQoGRWdy",
            "ZXNzEngKCnBlZXJlZF92cGMYASABKAsyYi5nb29nbGUuZXZlbnRzLmNsb3Vk",
            "LmJleW9uZGNvcnAuY2xpZW50Y29ubmVjdG9yc2VydmljZXMudjEuQ2xpZW50",
            "Q29ubmVjdG9yU2VydmljZS5FZ3Jlc3MuUGVlcmVkVnBjSAAaIAoJUGVlcmVk",
            "VnBjEhMKC25ldHdvcmtfdnBjGAEgASgJQhIKEGRlc3RpbmF0aW9uX3R5cGUi",
            "agoFU3RhdGUSFQoRU1RBVEVfVU5TUEVDSUZJRUQQABIMCghDUkVBVElORxAB",
            "EgwKCFVQREFUSU5HEAISDAoIREVMRVRJTkcQAxILCgdSVU5OSU5HEAQSCAoE",
            "RE9XThAFEgkKBUVSUk9SEAYilgEKH0NsaWVudENvbm5lY3RvclNlcnZpY2VF",
            "dmVudERhdGESZwoHcGF5bG9hZBgBIAEoCzJRLmdvb2dsZS5ldmVudHMuY2xv",
            "dWQuYmV5b25kY29ycC5jbGllbnRjb25uZWN0b3JzZXJ2aWNlcy52MS5DbGll",
            "bnRDb25uZWN0b3JTZXJ2aWNlSACIAQFCCgoIX3BheWxvYWRCwgGqAkJHb29n",
            "bGUuRXZlbnRzLlByb3RvYnVmLkNsb3VkLkJleW9uZENvcnAuQ2xpZW50Q29u",
            "bmVjdG9yU2VydmljZXMuVjHKAjlHb29nbGVcRXZlbnRzXENsb3VkXEJleW9u",
            "ZENvcnBcQ2xpZW50Q29ubmVjdG9yU2VydmljZXNcVjHqAj5Hb29nbGU6OkV2",
            "ZW50czo6Q2xvdWQ6OkJleW9uZENvcnA6OkNsaWVudENvbm5lY3RvclNlcnZp",
            "Y2VzOjpWMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService), global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Parser, new[]{ "Name", "CreateTime", "UpdateTime", "DisplayName", "Ingress", "Egress", "State" }, null, new[]{ typeof(global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.State) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress), global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Parser, new[]{ "Config" }, new[]{ "IngressConfig" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config), global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Parser, new[]{ "TransportProtocol", "DestinationRoutes" }, null, new[]{ typeof(global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.TransportProtocol) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.DestinationRoute), global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.DestinationRoute.Parser, new[]{ "Address", "Netmask" }, null, null, null, null)})}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress), global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress.Parser, new[]{ "PeeredVpc" }, new[]{ "DestinationType" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress.Types.PeeredVpc), global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress.Types.PeeredVpc.Parser, new[]{ "NetworkVpc" }, null, null, null, null)})}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorServiceEventData), global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorServiceEventData.Parser, new[]{ "Payload" }, new[]{ "Payload" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Message describing ClientConnectorService object.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClientConnectorService : pb::IMessage<ClientConnectorService>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClientConnectorService> _parser = new pb::MessageParser<ClientConnectorService>(() => new ClientConnectorService());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClientConnectorService> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.DataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientConnectorService() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientConnectorService(ClientConnectorService other) : this() {
      name_ = other.name_;
      createTime_ = other.createTime_ != null ? other.createTime_.Clone() : null;
      updateTime_ = other.updateTime_ != null ? other.updateTime_.Clone() : null;
      displayName_ = other.displayName_;
      ingress_ = other.ingress_ != null ? other.ingress_.Clone() : null;
      egress_ = other.egress_ != null ? other.egress_.Clone() : null;
      state_ = other.state_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientConnectorService Clone() {
      return new ClientConnectorService(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// Required. Name of resource. The name is ignored during creation.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "create_time" field.</summary>
    public const int CreateTimeFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createTime_;
    /// <summary>
    /// Output only. [Output only] Create time stamp.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreateTime {
      get { return createTime_; }
      set {
        createTime_ = value;
      }
    }

    /// <summary>Field number for the "update_time" field.</summary>
    public const int UpdateTimeFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp updateTime_;
    /// <summary>
    /// Output only. [Output only] Update time stamp.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp UpdateTime {
      get { return updateTime_; }
      set {
        updateTime_ = value;
      }
    }

    /// <summary>Field number for the "display_name" field.</summary>
    public const int DisplayNameFieldNumber = 4;
    private string displayName_ = "";
    /// <summary>
    /// Optional. User-provided name.
    /// The display name should follow certain format.
    /// * Must be 6 to 30 characters in length.
    /// * Can only contain lowercase letters, numbers, and hyphens.
    /// * Must start with a letter.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DisplayName {
      get { return displayName_; }
      set {
        displayName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ingress" field.</summary>
    public const int IngressFieldNumber = 6;
    private global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress ingress_;
    /// <summary>
    /// Required. The details of the ingress settings.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress Ingress {
      get { return ingress_; }
      set {
        ingress_ = value;
      }
    }

    /// <summary>Field number for the "egress" field.</summary>
    public const int EgressFieldNumber = 7;
    private global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress egress_;
    /// <summary>
    /// Required. The details of the egress settings.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress Egress {
      get { return egress_; }
      set {
        egress_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 8;
    private global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.State state_ = global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.State.Unspecified;
    /// <summary>
    /// Output only. The operational state of the ClientConnectorService.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.State State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClientConnectorService);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClientConnectorService other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(CreateTime, other.CreateTime)) return false;
      if (!object.Equals(UpdateTime, other.UpdateTime)) return false;
      if (DisplayName != other.DisplayName) return false;
      if (!object.Equals(Ingress, other.Ingress)) return false;
      if (!object.Equals(Egress, other.Egress)) return false;
      if (State != other.State) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (createTime_ != null) hash ^= CreateTime.GetHashCode();
      if (updateTime_ != null) hash ^= UpdateTime.GetHashCode();
      if (DisplayName.Length != 0) hash ^= DisplayName.GetHashCode();
      if (ingress_ != null) hash ^= Ingress.GetHashCode();
      if (egress_ != null) hash ^= Egress.GetHashCode();
      if (State != global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.State.Unspecified) hash ^= State.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (createTime_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CreateTime);
      }
      if (updateTime_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(UpdateTime);
      }
      if (DisplayName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(DisplayName);
      }
      if (ingress_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Ingress);
      }
      if (egress_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Egress);
      }
      if (State != global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.State.Unspecified) {
        output.WriteRawTag(64);
        output.WriteEnum((int) State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (createTime_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CreateTime);
      }
      if (updateTime_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(UpdateTime);
      }
      if (DisplayName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(DisplayName);
      }
      if (ingress_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Ingress);
      }
      if (egress_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Egress);
      }
      if (State != global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.State.Unspecified) {
        output.WriteRawTag(64);
        output.WriteEnum((int) State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (createTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreateTime);
      }
      if (updateTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateTime);
      }
      if (DisplayName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DisplayName);
      }
      if (ingress_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ingress);
      }
      if (egress_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Egress);
      }
      if (State != global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.State.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClientConnectorService other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.createTime_ != null) {
        if (createTime_ == null) {
          CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreateTime.MergeFrom(other.CreateTime);
      }
      if (other.updateTime_ != null) {
        if (updateTime_ == null) {
          UpdateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        UpdateTime.MergeFrom(other.UpdateTime);
      }
      if (other.DisplayName.Length != 0) {
        DisplayName = other.DisplayName;
      }
      if (other.ingress_ != null) {
        if (ingress_ == null) {
          Ingress = new global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress();
        }
        Ingress.MergeFrom(other.Ingress);
      }
      if (other.egress_ != null) {
        if (egress_ == null) {
          Egress = new global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress();
        }
        Egress.MergeFrom(other.Egress);
      }
      if (other.State != global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.State.Unspecified) {
        State = other.State;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (createTime_ == null) {
              CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreateTime);
            break;
          }
          case 26: {
            if (updateTime_ == null) {
              UpdateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(UpdateTime);
            break;
          }
          case 34: {
            DisplayName = input.ReadString();
            break;
          }
          case 50: {
            if (ingress_ == null) {
              Ingress = new global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress();
            }
            input.ReadMessage(Ingress);
            break;
          }
          case 58: {
            if (egress_ == null) {
              Egress = new global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress();
            }
            input.ReadMessage(Egress);
            break;
          }
          case 64: {
            State = (global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.State) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (createTime_ == null) {
              CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreateTime);
            break;
          }
          case 26: {
            if (updateTime_ == null) {
              UpdateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(UpdateTime);
            break;
          }
          case 34: {
            DisplayName = input.ReadString();
            break;
          }
          case 50: {
            if (ingress_ == null) {
              Ingress = new global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress();
            }
            input.ReadMessage(Ingress);
            break;
          }
          case 58: {
            if (egress_ == null) {
              Egress = new global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress();
            }
            input.ReadMessage(Egress);
            break;
          }
          case 64: {
            State = (global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.State) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ClientConnectorService message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Represents the different states of a ClientConnectorService.
      /// </summary>
      public enum State {
        /// <summary>
        /// Default value. This value is unused.
        /// </summary>
        [pbr::OriginalName("STATE_UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// ClientConnectorService is being created.
        /// </summary>
        [pbr::OriginalName("CREATING")] Creating = 1,
        /// <summary>
        /// ClientConnectorService is being updated.
        /// </summary>
        [pbr::OriginalName("UPDATING")] Updating = 2,
        /// <summary>
        /// ClientConnectorService is being deleted.
        /// </summary>
        [pbr::OriginalName("DELETING")] Deleting = 3,
        /// <summary>
        /// ClientConnectorService is running.
        /// </summary>
        [pbr::OriginalName("RUNNING")] Running = 4,
        /// <summary>
        /// ClientConnectorService is down and may be restored in the future.
        /// This happens when CCFE sends ProjectState = OFF.
        /// </summary>
        [pbr::OriginalName("DOWN")] Down = 5,
        /// <summary>
        /// ClientConnectorService encountered an error and is in an indeterministic
        /// state.
        /// </summary>
        [pbr::OriginalName("ERROR")] Error = 6,
      }

      /// <summary>
      /// Settings of how to connect to the ClientGateway.
      /// One of the following options should be set.
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Ingress : pb::IMessage<Ingress>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Ingress> _parser = new pb::MessageParser<Ingress>(() => new Ingress());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Ingress> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Ingress() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Ingress(Ingress other) : this() {
          switch (other.IngressConfigCase) {
            case IngressConfigOneofCase.Config:
              Config = other.Config.Clone();
              break;
          }

          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Ingress Clone() {
          return new Ingress(this);
        }

        /// <summary>Field number for the "config" field.</summary>
        public const int ConfigFieldNumber = 1;
        /// <summary>
        /// The basic ingress config for ClientGateways.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config Config {
          get { return ingressConfigCase_ == IngressConfigOneofCase.Config ? (global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config) ingressConfig_ : null; }
          set {
            ingressConfig_ = value;
            ingressConfigCase_ = value == null ? IngressConfigOneofCase.None : IngressConfigOneofCase.Config;
          }
        }

        private object ingressConfig_;
        /// <summary>Enum of possible cases for the "ingress_config" oneof.</summary>
        public enum IngressConfigOneofCase {
          None = 0,
          Config = 1,
        }
        private IngressConfigOneofCase ingressConfigCase_ = IngressConfigOneofCase.None;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public IngressConfigOneofCase IngressConfigCase {
          get { return ingressConfigCase_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearIngressConfig() {
          ingressConfigCase_ = IngressConfigOneofCase.None;
          ingressConfig_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Ingress);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Ingress other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(Config, other.Config)) return false;
          if (IngressConfigCase != other.IngressConfigCase) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ingressConfigCase_ == IngressConfigOneofCase.Config) hash ^= Config.GetHashCode();
          hash ^= (int) ingressConfigCase_;
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (ingressConfigCase_ == IngressConfigOneofCase.Config) {
            output.WriteRawTag(10);
            output.WriteMessage(Config);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (ingressConfigCase_ == IngressConfigOneofCase.Config) {
            output.WriteRawTag(10);
            output.WriteMessage(Config);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ingressConfigCase_ == IngressConfigOneofCase.Config) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Config);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Ingress other) {
          if (other == null) {
            return;
          }
          switch (other.IngressConfigCase) {
            case IngressConfigOneofCase.Config:
              if (Config == null) {
                Config = new global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config();
              }
              Config.MergeFrom(other.Config);
              break;
          }

          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config subBuilder = new global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config();
                if (ingressConfigCase_ == IngressConfigOneofCase.Config) {
                  subBuilder.MergeFrom(Config);
                }
                input.ReadMessage(subBuilder);
                Config = subBuilder;
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config subBuilder = new global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config();
                if (ingressConfigCase_ == IngressConfigOneofCase.Config) {
                  subBuilder.MergeFrom(Config);
                }
                input.ReadMessage(subBuilder);
                Config = subBuilder;
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the Ingress message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          /// <summary>
          /// The basic ingress config for ClientGateways.
          /// </summary>
          [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
          public sealed partial class Config : pb::IMessage<Config>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<Config> _parser = new pb::MessageParser<Config>(() => new Config());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<Config> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Config() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Config(Config other) : this() {
              transportProtocol_ = other.transportProtocol_;
              destinationRoutes_ = other.destinationRoutes_.Clone();
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public Config Clone() {
              return new Config(this);
            }

            /// <summary>Field number for the "transport_protocol" field.</summary>
            public const int TransportProtocolFieldNumber = 1;
            private global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.TransportProtocol transportProtocol_ = global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.TransportProtocol.Unspecified;
            /// <summary>
            /// Required. Immutable. The transport protocol used between the client and
            /// the server.
            /// </summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.TransportProtocol TransportProtocol {
              get { return transportProtocol_; }
              set {
                transportProtocol_ = value;
              }
            }

            /// <summary>Field number for the "destination_routes" field.</summary>
            public const int DestinationRoutesFieldNumber = 2;
            private static readonly pb::FieldCodec<global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.DestinationRoute> _repeated_destinationRoutes_codec
                = pb::FieldCodec.ForMessage(18, global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.DestinationRoute.Parser);
            private readonly pbc::RepeatedField<global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.DestinationRoute> destinationRoutes_ = new pbc::RepeatedField<global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.DestinationRoute>();
            /// <summary>
            /// Required. The settings used to configure basic ClientGateways.
            /// </summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public pbc::RepeatedField<global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.DestinationRoute> DestinationRoutes {
              get { return destinationRoutes_; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as Config);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(Config other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (TransportProtocol != other.TransportProtocol) return false;
              if(!destinationRoutes_.Equals(other.destinationRoutes_)) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (TransportProtocol != global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.TransportProtocol.Unspecified) hash ^= TransportProtocol.GetHashCode();
              hash ^= destinationRoutes_.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (TransportProtocol != global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.TransportProtocol.Unspecified) {
                output.WriteRawTag(8);
                output.WriteEnum((int) TransportProtocol);
              }
              destinationRoutes_.WriteTo(output, _repeated_destinationRoutes_codec);
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (TransportProtocol != global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.TransportProtocol.Unspecified) {
                output.WriteRawTag(8);
                output.WriteEnum((int) TransportProtocol);
              }
              destinationRoutes_.WriteTo(ref output, _repeated_destinationRoutes_codec);
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (TransportProtocol != global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.TransportProtocol.Unspecified) {
                size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TransportProtocol);
              }
              size += destinationRoutes_.CalculateSize(_repeated_destinationRoutes_codec);
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(Config other) {
              if (other == null) {
                return;
              }
              if (other.TransportProtocol != global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.TransportProtocol.Unspecified) {
                TransportProtocol = other.TransportProtocol;
              }
              destinationRoutes_.Add(other.destinationRoutes_);
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 8: {
                    TransportProtocol = (global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.TransportProtocol) input.ReadEnum();
                    break;
                  }
                  case 18: {
                    destinationRoutes_.AddEntriesFrom(input, _repeated_destinationRoutes_codec);
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 8: {
                    TransportProtocol = (global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Types.TransportProtocol) input.ReadEnum();
                    break;
                  }
                  case 18: {
                    destinationRoutes_.AddEntriesFrom(ref input, _repeated_destinationRoutes_codec);
                    break;
                  }
                }
              }
            }
            #endif

            #region Nested types
            /// <summary>Container for nested types declared in the Config message type.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static partial class Types {
              /// <summary>
              /// The protocol used to connect to the server.
              /// </summary>
              public enum TransportProtocol {
                /// <summary>
                /// Default value. This value is unused.
                /// </summary>
                [pbr::OriginalName("TRANSPORT_PROTOCOL_UNSPECIFIED")] Unspecified = 0,
                /// <summary>
                /// TCP protocol.
                /// </summary>
                [pbr::OriginalName("TCP")] Tcp = 1,
              }

              /// <summary>
              /// The setting used to configure ClientGateways.
              /// It is adding routes to the client's routing table
              /// after the connection is established.
              /// </summary>
              [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
              public sealed partial class DestinationRoute : pb::IMessage<DestinationRoute>
              #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                  , pb::IBufferMessage
              #endif
              {
                private static readonly pb::MessageParser<DestinationRoute> _parser = new pb::MessageParser<DestinationRoute>(() => new DestinationRoute());
                private pb::UnknownFieldSet _unknownFields;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public static pb::MessageParser<DestinationRoute> Parser { get { return _parser; } }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public static pbr::MessageDescriptor Descriptor {
                  get { return global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Ingress.Types.Config.Descriptor.NestedTypes[0]; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                pbr::MessageDescriptor pb::IMessage.Descriptor {
                  get { return Descriptor; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public DestinationRoute() {
                  OnConstruction();
                }

                partial void OnConstruction();

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public DestinationRoute(DestinationRoute other) : this() {
                  address_ = other.address_;
                  netmask_ = other.netmask_;
                  _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public DestinationRoute Clone() {
                  return new DestinationRoute(this);
                }

                /// <summary>Field number for the "address" field.</summary>
                public const int AddressFieldNumber = 1;
                private string address_ = "";
                /// <summary>
                /// Required. The network address of the subnet
                /// for which the packet is routed to the ClientGateway.
                /// </summary>
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public string Address {
                  get { return address_; }
                  set {
                    address_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                  }
                }

                /// <summary>Field number for the "netmask" field.</summary>
                public const int NetmaskFieldNumber = 2;
                private string netmask_ = "";
                /// <summary>
                /// Required. The network mask of the subnet
                /// for which the packet is routed to the ClientGateway.
                /// </summary>
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public string Netmask {
                  get { return netmask_; }
                  set {
                    netmask_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                  }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public override bool Equals(object other) {
                  return Equals(other as DestinationRoute);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public bool Equals(DestinationRoute other) {
                  if (ReferenceEquals(other, null)) {
                    return false;
                  }
                  if (ReferenceEquals(other, this)) {
                    return true;
                  }
                  if (Address != other.Address) return false;
                  if (Netmask != other.Netmask) return false;
                  return Equals(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public override int GetHashCode() {
                  int hash = 1;
                  if (Address.Length != 0) hash ^= Address.GetHashCode();
                  if (Netmask.Length != 0) hash ^= Netmask.GetHashCode();
                  if (_unknownFields != null) {
                    hash ^= _unknownFields.GetHashCode();
                  }
                  return hash;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public override string ToString() {
                  return pb::JsonFormatter.ToDiagnosticString(this);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public void WriteTo(pb::CodedOutputStream output) {
                #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                  output.WriteRawMessage(this);
                #else
                  if (Address.Length != 0) {
                    output.WriteRawTag(10);
                    output.WriteString(Address);
                  }
                  if (Netmask.Length != 0) {
                    output.WriteRawTag(18);
                    output.WriteString(Netmask);
                  }
                  if (_unknownFields != null) {
                    _unknownFields.WriteTo(output);
                  }
                #endif
                }

                #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
                  if (Address.Length != 0) {
                    output.WriteRawTag(10);
                    output.WriteString(Address);
                  }
                  if (Netmask.Length != 0) {
                    output.WriteRawTag(18);
                    output.WriteString(Netmask);
                  }
                  if (_unknownFields != null) {
                    _unknownFields.WriteTo(ref output);
                  }
                }
                #endif

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public int CalculateSize() {
                  int size = 0;
                  if (Address.Length != 0) {
                    size += 1 + pb::CodedOutputStream.ComputeStringSize(Address);
                  }
                  if (Netmask.Length != 0) {
                    size += 1 + pb::CodedOutputStream.ComputeStringSize(Netmask);
                  }
                  if (_unknownFields != null) {
                    size += _unknownFields.CalculateSize();
                  }
                  return size;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public void MergeFrom(DestinationRoute other) {
                  if (other == null) {
                    return;
                  }
                  if (other.Address.Length != 0) {
                    Address = other.Address;
                  }
                  if (other.Netmask.Length != 0) {
                    Netmask = other.Netmask;
                  }
                  _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                public void MergeFrom(pb::CodedInputStream input) {
                #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                  input.ReadRawMessage(this);
                #else
                  uint tag;
                  while ((tag = input.ReadTag()) != 0) {
                  if ((tag & 7) == 4) {
                    // Abort on any end group tag.
                    return;
                  }
                  switch(tag) {
                      default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                        break;
                      case 10: {
                        Address = input.ReadString();
                        break;
                      }
                      case 18: {
                        Netmask = input.ReadString();
                        break;
                      }
                    }
                  }
                #endif
                }

                #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
                void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
                  uint tag;
                  while ((tag = input.ReadTag()) != 0) {
                  if ((tag & 7) == 4) {
                    // Abort on any end group tag.
                    return;
                  }
                  switch(tag) {
                      default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                      case 10: {
                        Address = input.ReadString();
                        break;
                      }
                      case 18: {
                        Netmask = input.ReadString();
                        break;
                      }
                    }
                  }
                }
                #endif

              }

            }
            #endregion

          }

        }
        #endregion

      }

      /// <summary>
      /// The details of the egress info. One of the following options should be set.
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Egress : pb::IMessage<Egress>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Egress> _parser = new pb::MessageParser<Egress>(() => new Egress());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Egress> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Egress() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Egress(Egress other) : this() {
          switch (other.DestinationTypeCase) {
            case DestinationTypeOneofCase.PeeredVpc:
              PeeredVpc = other.PeeredVpc.Clone();
              break;
          }

          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Egress Clone() {
          return new Egress(this);
        }

        /// <summary>Field number for the "peered_vpc" field.</summary>
        public const int PeeredVpcFieldNumber = 1;
        /// <summary>
        /// A VPC from the consumer project.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress.Types.PeeredVpc PeeredVpc {
          get { return destinationTypeCase_ == DestinationTypeOneofCase.PeeredVpc ? (global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress.Types.PeeredVpc) destinationType_ : null; }
          set {
            destinationType_ = value;
            destinationTypeCase_ = value == null ? DestinationTypeOneofCase.None : DestinationTypeOneofCase.PeeredVpc;
          }
        }

        private object destinationType_;
        /// <summary>Enum of possible cases for the "destination_type" oneof.</summary>
        public enum DestinationTypeOneofCase {
          None = 0,
          PeeredVpc = 1,
        }
        private DestinationTypeOneofCase destinationTypeCase_ = DestinationTypeOneofCase.None;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DestinationTypeOneofCase DestinationTypeCase {
          get { return destinationTypeCase_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearDestinationType() {
          destinationTypeCase_ = DestinationTypeOneofCase.None;
          destinationType_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Egress);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Egress other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(PeeredVpc, other.PeeredVpc)) return false;
          if (DestinationTypeCase != other.DestinationTypeCase) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (destinationTypeCase_ == DestinationTypeOneofCase.PeeredVpc) hash ^= PeeredVpc.GetHashCode();
          hash ^= (int) destinationTypeCase_;
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (destinationTypeCase_ == DestinationTypeOneofCase.PeeredVpc) {
            output.WriteRawTag(10);
            output.WriteMessage(PeeredVpc);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (destinationTypeCase_ == DestinationTypeOneofCase.PeeredVpc) {
            output.WriteRawTag(10);
            output.WriteMessage(PeeredVpc);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (destinationTypeCase_ == DestinationTypeOneofCase.PeeredVpc) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(PeeredVpc);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Egress other) {
          if (other == null) {
            return;
          }
          switch (other.DestinationTypeCase) {
            case DestinationTypeOneofCase.PeeredVpc:
              if (PeeredVpc == null) {
                PeeredVpc = new global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress.Types.PeeredVpc();
              }
              PeeredVpc.MergeFrom(other.PeeredVpc);
              break;
          }

          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress.Types.PeeredVpc subBuilder = new global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress.Types.PeeredVpc();
                if (destinationTypeCase_ == DestinationTypeOneofCase.PeeredVpc) {
                  subBuilder.MergeFrom(PeeredVpc);
                }
                input.ReadMessage(subBuilder);
                PeeredVpc = subBuilder;
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress.Types.PeeredVpc subBuilder = new global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress.Types.PeeredVpc();
                if (destinationTypeCase_ == DestinationTypeOneofCase.PeeredVpc) {
                  subBuilder.MergeFrom(PeeredVpc);
                }
                input.ReadMessage(subBuilder);
                PeeredVpc = subBuilder;
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the Egress message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          /// <summary>
          /// The peered VPC owned by the consumer project.
          /// </summary>
          [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
          public sealed partial class PeeredVpc : pb::IMessage<PeeredVpc>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<PeeredVpc> _parser = new pb::MessageParser<PeeredVpc>(() => new PeeredVpc());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<PeeredVpc> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService.Types.Egress.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public PeeredVpc() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public PeeredVpc(PeeredVpc other) : this() {
              networkVpc_ = other.networkVpc_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public PeeredVpc Clone() {
              return new PeeredVpc(this);
            }

            /// <summary>Field number for the "network_vpc" field.</summary>
            public const int NetworkVpcFieldNumber = 1;
            private string networkVpc_ = "";
            /// <summary>
            /// Required. The name of the peered VPC owned by the consumer project.
            /// </summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string NetworkVpc {
              get { return networkVpc_; }
              set {
                networkVpc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as PeeredVpc);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(PeeredVpc other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (NetworkVpc != other.NetworkVpc) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (NetworkVpc.Length != 0) hash ^= NetworkVpc.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (NetworkVpc.Length != 0) {
                output.WriteRawTag(10);
                output.WriteString(NetworkVpc);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (NetworkVpc.Length != 0) {
                output.WriteRawTag(10);
                output.WriteString(NetworkVpc);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (NetworkVpc.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(NetworkVpc);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(PeeredVpc other) {
              if (other == null) {
                return;
              }
              if (other.NetworkVpc.Length != 0) {
                NetworkVpc = other.NetworkVpc;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    NetworkVpc = input.ReadString();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 10: {
                    NetworkVpc = input.ReadString();
                    break;
                  }
                }
              }
            }
            #endif

          }

        }
        #endregion

      }

    }
    #endregion

  }

  /// <summary>
  /// The data within all ClientConnectorService events.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClientConnectorServiceEventData : pb::IMessage<ClientConnectorServiceEventData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClientConnectorServiceEventData> _parser = new pb::MessageParser<ClientConnectorServiceEventData>(() => new ClientConnectorServiceEventData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClientConnectorServiceEventData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.DataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientConnectorServiceEventData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientConnectorServiceEventData(ClientConnectorServiceEventData other) : this() {
      payload_ = other.payload_ != null ? other.payload_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientConnectorServiceEventData Clone() {
      return new ClientConnectorServiceEventData(this);
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 1;
    private global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService payload_;
    /// <summary>
    /// Optional. The ClientConnectorService event payload. Unset for deletion
    /// events.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService Payload {
      get { return payload_; }
      set {
        payload_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClientConnectorServiceEventData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClientConnectorServiceEventData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Payload, other.Payload)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (payload_ != null) hash ^= Payload.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (payload_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Payload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (payload_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Payload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (payload_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Payload);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClientConnectorServiceEventData other) {
      if (other == null) {
        return;
      }
      if (other.payload_ != null) {
        if (payload_ == null) {
          Payload = new global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService();
        }
        Payload.MergeFrom(other.Payload);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (payload_ == null) {
              Payload = new global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService();
            }
            input.ReadMessage(Payload);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (payload_ == null) {
              Payload = new global::Google.Events.Protobuf.Cloud.BeyondCorp.ClientConnectorServices.V1.ClientConnectorService();
            }
            input.ReadMessage(Payload);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
