// Copyright 2023, Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/events/cloud/storage/v1/data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Events.Protobuf.Cloud.Storage.V1 {

  /// <summary>Holder for reflection information generated from google/events/cloud/storage/v1/data.proto</summary>
  public static partial class DataReflection {

    #region Descriptor
    /// <summary>File descriptor for google/events/cloud/storage/v1/data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cilnb29nbGUvZXZlbnRzL2Nsb3VkL3N0b3JhZ2UvdjEvZGF0YS5wcm90bxIe",
            "Z29vZ2xlLmV2ZW50cy5jbG91ZC5zdG9yYWdlLnYxGh9nb29nbGUvcHJvdG9i",
            "dWYvdGltZXN0YW1wLnByb3RvIpEIChFTdG9yYWdlT2JqZWN0RGF0YRIYChBj",
            "b250ZW50X2VuY29kaW5nGAEgASgJEhsKE2NvbnRlbnRfZGlzcG9zaXRpb24Y",
            "AiABKAkSFQoNY2FjaGVfY29udHJvbBgDIAEoCRIYChBjb250ZW50X2xhbmd1",
            "YWdlGAUgASgJEhYKDm1ldGFnZW5lcmF0aW9uGAYgASgDEjAKDHRpbWVfZGVs",
            "ZXRlZBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASFAoMY29u",
            "dGVudF90eXBlGAggASgJEgwKBHNpemUYCSABKAMSMAoMdGltZV9jcmVhdGVk",
            "GAogASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIOCgZjcmMzMmMY",
            "CyABKAkSFwoPY29tcG9uZW50X2NvdW50GAwgASgFEhAKCG1kNV9oYXNoGA0g",
            "ASgJEgwKBGV0YWcYDiABKAkSKwoHdXBkYXRlZBgPIAEoCzIaLmdvb2dsZS5w",
            "cm90b2J1Zi5UaW1lc3RhbXASFQoNc3RvcmFnZV9jbGFzcxgQIAEoCRIUCgxr",
            "bXNfa2V5X25hbWUYESABKAkSPgoadGltZV9zdG9yYWdlX2NsYXNzX3VwZGF0",
            "ZWQYEiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhYKDnRlbXBv",
            "cmFyeV9ob2xkGBMgASgIEj0KGXJldGVudGlvbl9leHBpcmF0aW9uX3RpbWUY",
            "FCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wElEKCG1ldGFkYXRh",
            "GBUgAygLMj8uZ29vZ2xlLmV2ZW50cy5jbG91ZC5zdG9yYWdlLnYxLlN0b3Jh",
            "Z2VPYmplY3REYXRhLk1ldGFkYXRhRW50cnkSGAoQZXZlbnRfYmFzZWRfaG9s",
            "ZBgdIAEoCBIMCgRuYW1lGBcgASgJEgoKAmlkGBggASgJEg4KBmJ1Y2tldBgZ",
            "IAEoCRISCgpnZW5lcmF0aW9uGBogASgDEmEKE2N1c3RvbWVyX2VuY3J5cHRp",
            "b24YHCABKAsyRC5nb29nbGUuZXZlbnRzLmNsb3VkLnN0b3JhZ2UudjEuU3Rv",
            "cmFnZU9iamVjdERhdGEuQ3VzdG9tZXJFbmNyeXB0aW9uEhIKCm1lZGlhX2xp",
            "bmsYZCABKAkSEQoJc2VsZl9saW5rGGUgASgJEgwKBGtpbmQYZiABKAkaRgoS",
            "Q3VzdG9tZXJFbmNyeXB0aW9uEhwKFGVuY3J5cHRpb25fYWxnb3JpdGhtGAEg",
            "ASgJEhIKCmtleV9zaGEyNTYYAiABKAkaLwoNTWV0YWRhdGFFbnRyeRILCgNr",
            "ZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQiqqAidHb29nbGUuRXZlbnRz",
            "LlByb3RvYnVmLkNsb3VkLlN0b3JhZ2UuVjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObjectData), global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObjectData.Parser, new[]{ "ContentEncoding", "ContentDisposition", "CacheControl", "ContentLanguage", "Metageneration", "TimeDeleted", "ContentType", "Size", "TimeCreated", "Crc32C", "ComponentCount", "Md5Hash", "Etag", "Updated", "StorageClass", "KmsKeyName", "TimeStorageClassUpdated", "TemporaryHold", "RetentionExpirationTime", "Metadata", "EventBasedHold", "Name", "Id", "Bucket", "Generation", "CustomerEncryption", "MediaLink", "SelfLink", "Kind" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObjectData.Types.CustomerEncryption), global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObjectData.Types.CustomerEncryption.Parser, new[]{ "EncryptionAlgorithm", "KeySha256" }, null, null, null, null),
            null, })
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// An object within Google Cloud Storage.
  /// </summary>
  public sealed partial class StorageObjectData : pb::IMessage<StorageObjectData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StorageObjectData> _parser = new pb::MessageParser<StorageObjectData>(() => new StorageObjectData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StorageObjectData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Events.Protobuf.Cloud.Storage.V1.DataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StorageObjectData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StorageObjectData(StorageObjectData other) : this() {
      contentEncoding_ = other.contentEncoding_;
      contentDisposition_ = other.contentDisposition_;
      cacheControl_ = other.cacheControl_;
      contentLanguage_ = other.contentLanguage_;
      metageneration_ = other.metageneration_;
      timeDeleted_ = other.timeDeleted_ != null ? other.timeDeleted_.Clone() : null;
      contentType_ = other.contentType_;
      size_ = other.size_;
      timeCreated_ = other.timeCreated_ != null ? other.timeCreated_.Clone() : null;
      crc32C_ = other.crc32C_;
      componentCount_ = other.componentCount_;
      md5Hash_ = other.md5Hash_;
      etag_ = other.etag_;
      updated_ = other.updated_ != null ? other.updated_.Clone() : null;
      storageClass_ = other.storageClass_;
      kmsKeyName_ = other.kmsKeyName_;
      timeStorageClassUpdated_ = other.timeStorageClassUpdated_ != null ? other.timeStorageClassUpdated_.Clone() : null;
      temporaryHold_ = other.temporaryHold_;
      retentionExpirationTime_ = other.retentionExpirationTime_ != null ? other.retentionExpirationTime_.Clone() : null;
      metadata_ = other.metadata_.Clone();
      eventBasedHold_ = other.eventBasedHold_;
      name_ = other.name_;
      id_ = other.id_;
      bucket_ = other.bucket_;
      generation_ = other.generation_;
      customerEncryption_ = other.customerEncryption_ != null ? other.customerEncryption_.Clone() : null;
      mediaLink_ = other.mediaLink_;
      selfLink_ = other.selfLink_;
      kind_ = other.kind_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StorageObjectData Clone() {
      return new StorageObjectData(this);
    }

    /// <summary>Field number for the "content_encoding" field.</summary>
    public const int ContentEncodingFieldNumber = 1;
    private string contentEncoding_ = "";
    /// <summary>
    /// Content-Encoding of the object data, matching
    /// [https://tools.ietf.org/html/rfc7231#section-3.1.2.2][RFC 7231 §3.1.2.2]
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ContentEncoding {
      get { return contentEncoding_; }
      set {
        contentEncoding_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "content_disposition" field.</summary>
    public const int ContentDispositionFieldNumber = 2;
    private string contentDisposition_ = "";
    /// <summary>
    /// Content-Disposition of the object data, matching
    /// [https://tools.ietf.org/html/rfc6266][RFC 6266].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ContentDisposition {
      get { return contentDisposition_; }
      set {
        contentDisposition_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cache_control" field.</summary>
    public const int CacheControlFieldNumber = 3;
    private string cacheControl_ = "";
    /// <summary>
    /// Cache-Control directive for the object data, matching
    /// [https://tools.ietf.org/html/rfc7234#section-5.2"][RFC 7234 §5.2].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CacheControl {
      get { return cacheControl_; }
      set {
        cacheControl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "content_language" field.</summary>
    public const int ContentLanguageFieldNumber = 5;
    private string contentLanguage_ = "";
    /// <summary>
    /// Content-Language of the object data, matching
    /// [https://tools.ietf.org/html/rfc7231#section-3.1.3.2][RFC 7231 §3.1.3.2].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ContentLanguage {
      get { return contentLanguage_; }
      set {
        contentLanguage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "metageneration" field.</summary>
    public const int MetagenerationFieldNumber = 6;
    private long metageneration_;
    /// <summary>
    /// The version of the metadata for this object at this generation. Used for
    /// preconditions and for detecting changes in metadata. A metageneration
    /// number is only meaningful in the context of a particular generation of a
    /// particular object.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Metageneration {
      get { return metageneration_; }
      set {
        metageneration_ = value;
      }
    }

    /// <summary>Field number for the "time_deleted" field.</summary>
    public const int TimeDeletedFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timeDeleted_;
    /// <summary>
    /// The deletion time of the object. Will be returned if and only if this
    /// version of the object has been deleted.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimeDeleted {
      get { return timeDeleted_; }
      set {
        timeDeleted_ = value;
      }
    }

    /// <summary>Field number for the "content_type" field.</summary>
    public const int ContentTypeFieldNumber = 8;
    private string contentType_ = "";
    /// <summary>
    /// Content-Type of the object data, matching
    /// [https://tools.ietf.org/html/rfc7231#section-3.1.1.5][RFC 7231 §3.1.1.5].
    /// If an object is stored without a Content-Type, it is served as
    /// `application/octet-stream`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ContentType {
      get { return contentType_; }
      set {
        contentType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "size" field.</summary>
    public const int SizeFieldNumber = 9;
    private long size_;
    /// <summary>
    /// Content-Length of the object data in bytes, matching
    /// [https://tools.ietf.org/html/rfc7230#section-3.3.2][RFC 7230 §3.3.2].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Size {
      get { return size_; }
      set {
        size_ = value;
      }
    }

    /// <summary>Field number for the "time_created" field.</summary>
    public const int TimeCreatedFieldNumber = 10;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timeCreated_;
    /// <summary>
    /// The creation time of the object.
    /// Attempting to set this field will result in an error.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimeCreated {
      get { return timeCreated_; }
      set {
        timeCreated_ = value;
      }
    }

    /// <summary>Field number for the "crc32c" field.</summary>
    public const int Crc32CFieldNumber = 11;
    private string crc32C_ = "";
    /// <summary>
    /// CRC32c checksum. For more information about using the CRC32c
    /// checksum, see
    /// [https://cloud.google.com/storage/docs/hashes-etags#_JSONAPI][Hashes and
    /// ETags: Best Practices].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Crc32C {
      get { return crc32C_; }
      set {
        crc32C_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "component_count" field.</summary>
    public const int ComponentCountFieldNumber = 12;
    private int componentCount_;
    /// <summary>
    /// Number of underlying components that make up this object. Components are
    /// accumulated by compose operations.
    /// Attempting to set this field will result in an error.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ComponentCount {
      get { return componentCount_; }
      set {
        componentCount_ = value;
      }
    }

    /// <summary>Field number for the "md5_hash" field.</summary>
    public const int Md5HashFieldNumber = 13;
    private string md5Hash_ = "";
    /// <summary>
    /// MD5 hash of the data; encoded using base64 as per
    /// [https://tools.ietf.org/html/rfc4648#section-4][RFC 4648 §4]. For more
    /// information about using the MD5 hash, see
    /// [https://cloud.google.com/storage/docs/hashes-etags#_JSONAPI][Hashes and
    /// ETags: Best Practices].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Md5Hash {
      get { return md5Hash_; }
      set {
        md5Hash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "etag" field.</summary>
    public const int EtagFieldNumber = 14;
    private string etag_ = "";
    /// <summary>
    /// HTTP 1.1 Entity tag for the object. See
    /// [https://tools.ietf.org/html/rfc7232#section-2.3][RFC 7232 §2.3].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Etag {
      get { return etag_; }
      set {
        etag_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "updated" field.</summary>
    public const int UpdatedFieldNumber = 15;
    private global::Google.Protobuf.WellKnownTypes.Timestamp updated_;
    /// <summary>
    /// The modification time of the object metadata.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Updated {
      get { return updated_; }
      set {
        updated_ = value;
      }
    }

    /// <summary>Field number for the "storage_class" field.</summary>
    public const int StorageClassFieldNumber = 16;
    private string storageClass_ = "";
    /// <summary>
    /// Storage class of the object.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StorageClass {
      get { return storageClass_; }
      set {
        storageClass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "kms_key_name" field.</summary>
    public const int KmsKeyNameFieldNumber = 17;
    private string kmsKeyName_ = "";
    /// <summary>
    /// Cloud KMS Key used to encrypt this object, if the object is encrypted by
    /// such a key.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string KmsKeyName {
      get { return kmsKeyName_; }
      set {
        kmsKeyName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "time_storage_class_updated" field.</summary>
    public const int TimeStorageClassUpdatedFieldNumber = 18;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timeStorageClassUpdated_;
    /// <summary>
    /// The time at which the object's storage class was last changed.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimeStorageClassUpdated {
      get { return timeStorageClassUpdated_; }
      set {
        timeStorageClassUpdated_ = value;
      }
    }

    /// <summary>Field number for the "temporary_hold" field.</summary>
    public const int TemporaryHoldFieldNumber = 19;
    private bool temporaryHold_;
    /// <summary>
    /// Whether an object is under temporary hold.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool TemporaryHold {
      get { return temporaryHold_; }
      set {
        temporaryHold_ = value;
      }
    }

    /// <summary>Field number for the "retention_expiration_time" field.</summary>
    public const int RetentionExpirationTimeFieldNumber = 20;
    private global::Google.Protobuf.WellKnownTypes.Timestamp retentionExpirationTime_;
    /// <summary>
    /// A server-determined value that specifies the earliest time that the
    /// object's retention period expires.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp RetentionExpirationTime {
      get { return retentionExpirationTime_; }
      set {
        retentionExpirationTime_ = value;
      }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 21;
    private static readonly pbc::MapField<string, string>.Codec _map_metadata_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 170);
    private readonly pbc::MapField<string, string> metadata_ = new pbc::MapField<string, string>();
    /// <summary>
    /// User-provided metadata, in key/value pairs.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Metadata {
      get { return metadata_; }
    }

    /// <summary>Field number for the "event_based_hold" field.</summary>
    public const int EventBasedHoldFieldNumber = 29;
    private bool eventBasedHold_;
    /// <summary>
    /// Whether an object is under event-based hold.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EventBasedHold {
      get { return eventBasedHold_; }
      set {
        eventBasedHold_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 23;
    private string name_ = "";
    /// <summary>
    /// The name of the object.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 24;
    private string id_ = "";
    /// <summary>
    /// The ID of the object, including the bucket name, object name, and
    /// generation number.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bucket" field.</summary>
    public const int BucketFieldNumber = 25;
    private string bucket_ = "";
    /// <summary>
    /// The name of the bucket containing this object.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Bucket {
      get { return bucket_; }
      set {
        bucket_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "generation" field.</summary>
    public const int GenerationFieldNumber = 26;
    private long generation_;
    /// <summary>
    /// The content generation of this object. Used for object versioning.
    /// Attempting to set this field will result in an error.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Generation {
      get { return generation_; }
      set {
        generation_ = value;
      }
    }

    /// <summary>Field number for the "customer_encryption" field.</summary>
    public const int CustomerEncryptionFieldNumber = 28;
    private global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObjectData.Types.CustomerEncryption customerEncryption_;
    /// <summary>
    /// Metadata of customer-supplied encryption key, if the object is encrypted by
    /// such a key.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObjectData.Types.CustomerEncryption CustomerEncryption {
      get { return customerEncryption_; }
      set {
        customerEncryption_ = value;
      }
    }

    /// <summary>Field number for the "media_link" field.</summary>
    public const int MediaLinkFieldNumber = 100;
    private string mediaLink_ = "";
    /// <summary>
    /// Media download link.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MediaLink {
      get { return mediaLink_; }
      set {
        mediaLink_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "self_link" field.</summary>
    public const int SelfLinkFieldNumber = 101;
    private string selfLink_ = "";
    /// <summary>
    /// The link to this object.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SelfLink {
      get { return selfLink_; }
      set {
        selfLink_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "kind" field.</summary>
    public const int KindFieldNumber = 102;
    private string kind_ = "";
    /// <summary>
    /// The kind of item this is. For objects, this is always "storage#object".
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Kind {
      get { return kind_; }
      set {
        kind_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StorageObjectData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StorageObjectData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ContentEncoding != other.ContentEncoding) return false;
      if (ContentDisposition != other.ContentDisposition) return false;
      if (CacheControl != other.CacheControl) return false;
      if (ContentLanguage != other.ContentLanguage) return false;
      if (Metageneration != other.Metageneration) return false;
      if (!object.Equals(TimeDeleted, other.TimeDeleted)) return false;
      if (ContentType != other.ContentType) return false;
      if (Size != other.Size) return false;
      if (!object.Equals(TimeCreated, other.TimeCreated)) return false;
      if (Crc32C != other.Crc32C) return false;
      if (ComponentCount != other.ComponentCount) return false;
      if (Md5Hash != other.Md5Hash) return false;
      if (Etag != other.Etag) return false;
      if (!object.Equals(Updated, other.Updated)) return false;
      if (StorageClass != other.StorageClass) return false;
      if (KmsKeyName != other.KmsKeyName) return false;
      if (!object.Equals(TimeStorageClassUpdated, other.TimeStorageClassUpdated)) return false;
      if (TemporaryHold != other.TemporaryHold) return false;
      if (!object.Equals(RetentionExpirationTime, other.RetentionExpirationTime)) return false;
      if (!Metadata.Equals(other.Metadata)) return false;
      if (EventBasedHold != other.EventBasedHold) return false;
      if (Name != other.Name) return false;
      if (Id != other.Id) return false;
      if (Bucket != other.Bucket) return false;
      if (Generation != other.Generation) return false;
      if (!object.Equals(CustomerEncryption, other.CustomerEncryption)) return false;
      if (MediaLink != other.MediaLink) return false;
      if (SelfLink != other.SelfLink) return false;
      if (Kind != other.Kind) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ContentEncoding.Length != 0) hash ^= ContentEncoding.GetHashCode();
      if (ContentDisposition.Length != 0) hash ^= ContentDisposition.GetHashCode();
      if (CacheControl.Length != 0) hash ^= CacheControl.GetHashCode();
      if (ContentLanguage.Length != 0) hash ^= ContentLanguage.GetHashCode();
      if (Metageneration != 0L) hash ^= Metageneration.GetHashCode();
      if (timeDeleted_ != null) hash ^= TimeDeleted.GetHashCode();
      if (ContentType.Length != 0) hash ^= ContentType.GetHashCode();
      if (Size != 0L) hash ^= Size.GetHashCode();
      if (timeCreated_ != null) hash ^= TimeCreated.GetHashCode();
      if (Crc32C.Length != 0) hash ^= Crc32C.GetHashCode();
      if (ComponentCount != 0) hash ^= ComponentCount.GetHashCode();
      if (Md5Hash.Length != 0) hash ^= Md5Hash.GetHashCode();
      if (Etag.Length != 0) hash ^= Etag.GetHashCode();
      if (updated_ != null) hash ^= Updated.GetHashCode();
      if (StorageClass.Length != 0) hash ^= StorageClass.GetHashCode();
      if (KmsKeyName.Length != 0) hash ^= KmsKeyName.GetHashCode();
      if (timeStorageClassUpdated_ != null) hash ^= TimeStorageClassUpdated.GetHashCode();
      if (TemporaryHold != false) hash ^= TemporaryHold.GetHashCode();
      if (retentionExpirationTime_ != null) hash ^= RetentionExpirationTime.GetHashCode();
      hash ^= Metadata.GetHashCode();
      if (EventBasedHold != false) hash ^= EventBasedHold.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Bucket.Length != 0) hash ^= Bucket.GetHashCode();
      if (Generation != 0L) hash ^= Generation.GetHashCode();
      if (customerEncryption_ != null) hash ^= CustomerEncryption.GetHashCode();
      if (MediaLink.Length != 0) hash ^= MediaLink.GetHashCode();
      if (SelfLink.Length != 0) hash ^= SelfLink.GetHashCode();
      if (Kind.Length != 0) hash ^= Kind.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ContentEncoding.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ContentEncoding);
      }
      if (ContentDisposition.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ContentDisposition);
      }
      if (CacheControl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CacheControl);
      }
      if (ContentLanguage.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ContentLanguage);
      }
      if (Metageneration != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Metageneration);
      }
      if (timeDeleted_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(TimeDeleted);
      }
      if (ContentType.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ContentType);
      }
      if (Size != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(Size);
      }
      if (timeCreated_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(TimeCreated);
      }
      if (Crc32C.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Crc32C);
      }
      if (ComponentCount != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(ComponentCount);
      }
      if (Md5Hash.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Md5Hash);
      }
      if (Etag.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(Etag);
      }
      if (updated_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(Updated);
      }
      if (StorageClass.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(StorageClass);
      }
      if (KmsKeyName.Length != 0) {
        output.WriteRawTag(138, 1);
        output.WriteString(KmsKeyName);
      }
      if (timeStorageClassUpdated_ != null) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(TimeStorageClassUpdated);
      }
      if (TemporaryHold != false) {
        output.WriteRawTag(152, 1);
        output.WriteBool(TemporaryHold);
      }
      if (retentionExpirationTime_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(RetentionExpirationTime);
      }
      metadata_.WriteTo(output, _map_metadata_codec);
      if (Name.Length != 0) {
        output.WriteRawTag(186, 1);
        output.WriteString(Name);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(194, 1);
        output.WriteString(Id);
      }
      if (Bucket.Length != 0) {
        output.WriteRawTag(202, 1);
        output.WriteString(Bucket);
      }
      if (Generation != 0L) {
        output.WriteRawTag(208, 1);
        output.WriteInt64(Generation);
      }
      if (customerEncryption_ != null) {
        output.WriteRawTag(226, 1);
        output.WriteMessage(CustomerEncryption);
      }
      if (EventBasedHold != false) {
        output.WriteRawTag(232, 1);
        output.WriteBool(EventBasedHold);
      }
      if (MediaLink.Length != 0) {
        output.WriteRawTag(162, 6);
        output.WriteString(MediaLink);
      }
      if (SelfLink.Length != 0) {
        output.WriteRawTag(170, 6);
        output.WriteString(SelfLink);
      }
      if (Kind.Length != 0) {
        output.WriteRawTag(178, 6);
        output.WriteString(Kind);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ContentEncoding.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ContentEncoding);
      }
      if (ContentDisposition.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ContentDisposition);
      }
      if (CacheControl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CacheControl);
      }
      if (ContentLanguage.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ContentLanguage);
      }
      if (Metageneration != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Metageneration);
      }
      if (timeDeleted_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(TimeDeleted);
      }
      if (ContentType.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ContentType);
      }
      if (Size != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(Size);
      }
      if (timeCreated_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(TimeCreated);
      }
      if (Crc32C.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Crc32C);
      }
      if (ComponentCount != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(ComponentCount);
      }
      if (Md5Hash.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Md5Hash);
      }
      if (Etag.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(Etag);
      }
      if (updated_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(Updated);
      }
      if (StorageClass.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(StorageClass);
      }
      if (KmsKeyName.Length != 0) {
        output.WriteRawTag(138, 1);
        output.WriteString(KmsKeyName);
      }
      if (timeStorageClassUpdated_ != null) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(TimeStorageClassUpdated);
      }
      if (TemporaryHold != false) {
        output.WriteRawTag(152, 1);
        output.WriteBool(TemporaryHold);
      }
      if (retentionExpirationTime_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(RetentionExpirationTime);
      }
      metadata_.WriteTo(ref output, _map_metadata_codec);
      if (Name.Length != 0) {
        output.WriteRawTag(186, 1);
        output.WriteString(Name);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(194, 1);
        output.WriteString(Id);
      }
      if (Bucket.Length != 0) {
        output.WriteRawTag(202, 1);
        output.WriteString(Bucket);
      }
      if (Generation != 0L) {
        output.WriteRawTag(208, 1);
        output.WriteInt64(Generation);
      }
      if (customerEncryption_ != null) {
        output.WriteRawTag(226, 1);
        output.WriteMessage(CustomerEncryption);
      }
      if (EventBasedHold != false) {
        output.WriteRawTag(232, 1);
        output.WriteBool(EventBasedHold);
      }
      if (MediaLink.Length != 0) {
        output.WriteRawTag(162, 6);
        output.WriteString(MediaLink);
      }
      if (SelfLink.Length != 0) {
        output.WriteRawTag(170, 6);
        output.WriteString(SelfLink);
      }
      if (Kind.Length != 0) {
        output.WriteRawTag(178, 6);
        output.WriteString(Kind);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ContentEncoding.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContentEncoding);
      }
      if (ContentDisposition.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContentDisposition);
      }
      if (CacheControl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CacheControl);
      }
      if (ContentLanguage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContentLanguage);
      }
      if (Metageneration != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Metageneration);
      }
      if (timeDeleted_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeDeleted);
      }
      if (ContentType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContentType);
      }
      if (Size != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Size);
      }
      if (timeCreated_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeCreated);
      }
      if (Crc32C.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Crc32C);
      }
      if (ComponentCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ComponentCount);
      }
      if (Md5Hash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Md5Hash);
      }
      if (Etag.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Etag);
      }
      if (updated_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Updated);
      }
      if (StorageClass.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(StorageClass);
      }
      if (KmsKeyName.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(KmsKeyName);
      }
      if (timeStorageClassUpdated_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(TimeStorageClassUpdated);
      }
      if (TemporaryHold != false) {
        size += 2 + 1;
      }
      if (retentionExpirationTime_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(RetentionExpirationTime);
      }
      size += metadata_.CalculateSize(_map_metadata_codec);
      if (EventBasedHold != false) {
        size += 2 + 1;
      }
      if (Name.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Id.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Bucket.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Bucket);
      }
      if (Generation != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Generation);
      }
      if (customerEncryption_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(CustomerEncryption);
      }
      if (MediaLink.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(MediaLink);
      }
      if (SelfLink.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(SelfLink);
      }
      if (Kind.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Kind);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StorageObjectData other) {
      if (other == null) {
        return;
      }
      if (other.ContentEncoding.Length != 0) {
        ContentEncoding = other.ContentEncoding;
      }
      if (other.ContentDisposition.Length != 0) {
        ContentDisposition = other.ContentDisposition;
      }
      if (other.CacheControl.Length != 0) {
        CacheControl = other.CacheControl;
      }
      if (other.ContentLanguage.Length != 0) {
        ContentLanguage = other.ContentLanguage;
      }
      if (other.Metageneration != 0L) {
        Metageneration = other.Metageneration;
      }
      if (other.timeDeleted_ != null) {
        if (timeDeleted_ == null) {
          TimeDeleted = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TimeDeleted.MergeFrom(other.TimeDeleted);
      }
      if (other.ContentType.Length != 0) {
        ContentType = other.ContentType;
      }
      if (other.Size != 0L) {
        Size = other.Size;
      }
      if (other.timeCreated_ != null) {
        if (timeCreated_ == null) {
          TimeCreated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TimeCreated.MergeFrom(other.TimeCreated);
      }
      if (other.Crc32C.Length != 0) {
        Crc32C = other.Crc32C;
      }
      if (other.ComponentCount != 0) {
        ComponentCount = other.ComponentCount;
      }
      if (other.Md5Hash.Length != 0) {
        Md5Hash = other.Md5Hash;
      }
      if (other.Etag.Length != 0) {
        Etag = other.Etag;
      }
      if (other.updated_ != null) {
        if (updated_ == null) {
          Updated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Updated.MergeFrom(other.Updated);
      }
      if (other.StorageClass.Length != 0) {
        StorageClass = other.StorageClass;
      }
      if (other.KmsKeyName.Length != 0) {
        KmsKeyName = other.KmsKeyName;
      }
      if (other.timeStorageClassUpdated_ != null) {
        if (timeStorageClassUpdated_ == null) {
          TimeStorageClassUpdated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TimeStorageClassUpdated.MergeFrom(other.TimeStorageClassUpdated);
      }
      if (other.TemporaryHold != false) {
        TemporaryHold = other.TemporaryHold;
      }
      if (other.retentionExpirationTime_ != null) {
        if (retentionExpirationTime_ == null) {
          RetentionExpirationTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        RetentionExpirationTime.MergeFrom(other.RetentionExpirationTime);
      }
      metadata_.MergeFrom(other.metadata_);
      if (other.EventBasedHold != false) {
        EventBasedHold = other.EventBasedHold;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Bucket.Length != 0) {
        Bucket = other.Bucket;
      }
      if (other.Generation != 0L) {
        Generation = other.Generation;
      }
      if (other.customerEncryption_ != null) {
        if (customerEncryption_ == null) {
          CustomerEncryption = new global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObjectData.Types.CustomerEncryption();
        }
        CustomerEncryption.MergeFrom(other.CustomerEncryption);
      }
      if (other.MediaLink.Length != 0) {
        MediaLink = other.MediaLink;
      }
      if (other.SelfLink.Length != 0) {
        SelfLink = other.SelfLink;
      }
      if (other.Kind.Length != 0) {
        Kind = other.Kind;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ContentEncoding = input.ReadString();
            break;
          }
          case 18: {
            ContentDisposition = input.ReadString();
            break;
          }
          case 26: {
            CacheControl = input.ReadString();
            break;
          }
          case 42: {
            ContentLanguage = input.ReadString();
            break;
          }
          case 48: {
            Metageneration = input.ReadInt64();
            break;
          }
          case 58: {
            if (timeDeleted_ == null) {
              TimeDeleted = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimeDeleted);
            break;
          }
          case 66: {
            ContentType = input.ReadString();
            break;
          }
          case 72: {
            Size = input.ReadInt64();
            break;
          }
          case 82: {
            if (timeCreated_ == null) {
              TimeCreated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimeCreated);
            break;
          }
          case 90: {
            Crc32C = input.ReadString();
            break;
          }
          case 96: {
            ComponentCount = input.ReadInt32();
            break;
          }
          case 106: {
            Md5Hash = input.ReadString();
            break;
          }
          case 114: {
            Etag = input.ReadString();
            break;
          }
          case 122: {
            if (updated_ == null) {
              Updated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Updated);
            break;
          }
          case 130: {
            StorageClass = input.ReadString();
            break;
          }
          case 138: {
            KmsKeyName = input.ReadString();
            break;
          }
          case 146: {
            if (timeStorageClassUpdated_ == null) {
              TimeStorageClassUpdated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimeStorageClassUpdated);
            break;
          }
          case 152: {
            TemporaryHold = input.ReadBool();
            break;
          }
          case 162: {
            if (retentionExpirationTime_ == null) {
              RetentionExpirationTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(RetentionExpirationTime);
            break;
          }
          case 170: {
            metadata_.AddEntriesFrom(input, _map_metadata_codec);
            break;
          }
          case 186: {
            Name = input.ReadString();
            break;
          }
          case 194: {
            Id = input.ReadString();
            break;
          }
          case 202: {
            Bucket = input.ReadString();
            break;
          }
          case 208: {
            Generation = input.ReadInt64();
            break;
          }
          case 226: {
            if (customerEncryption_ == null) {
              CustomerEncryption = new global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObjectData.Types.CustomerEncryption();
            }
            input.ReadMessage(CustomerEncryption);
            break;
          }
          case 232: {
            EventBasedHold = input.ReadBool();
            break;
          }
          case 802: {
            MediaLink = input.ReadString();
            break;
          }
          case 810: {
            SelfLink = input.ReadString();
            break;
          }
          case 818: {
            Kind = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ContentEncoding = input.ReadString();
            break;
          }
          case 18: {
            ContentDisposition = input.ReadString();
            break;
          }
          case 26: {
            CacheControl = input.ReadString();
            break;
          }
          case 42: {
            ContentLanguage = input.ReadString();
            break;
          }
          case 48: {
            Metageneration = input.ReadInt64();
            break;
          }
          case 58: {
            if (timeDeleted_ == null) {
              TimeDeleted = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimeDeleted);
            break;
          }
          case 66: {
            ContentType = input.ReadString();
            break;
          }
          case 72: {
            Size = input.ReadInt64();
            break;
          }
          case 82: {
            if (timeCreated_ == null) {
              TimeCreated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimeCreated);
            break;
          }
          case 90: {
            Crc32C = input.ReadString();
            break;
          }
          case 96: {
            ComponentCount = input.ReadInt32();
            break;
          }
          case 106: {
            Md5Hash = input.ReadString();
            break;
          }
          case 114: {
            Etag = input.ReadString();
            break;
          }
          case 122: {
            if (updated_ == null) {
              Updated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Updated);
            break;
          }
          case 130: {
            StorageClass = input.ReadString();
            break;
          }
          case 138: {
            KmsKeyName = input.ReadString();
            break;
          }
          case 146: {
            if (timeStorageClassUpdated_ == null) {
              TimeStorageClassUpdated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TimeStorageClassUpdated);
            break;
          }
          case 152: {
            TemporaryHold = input.ReadBool();
            break;
          }
          case 162: {
            if (retentionExpirationTime_ == null) {
              RetentionExpirationTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(RetentionExpirationTime);
            break;
          }
          case 170: {
            metadata_.AddEntriesFrom(ref input, _map_metadata_codec);
            break;
          }
          case 186: {
            Name = input.ReadString();
            break;
          }
          case 194: {
            Id = input.ReadString();
            break;
          }
          case 202: {
            Bucket = input.ReadString();
            break;
          }
          case 208: {
            Generation = input.ReadInt64();
            break;
          }
          case 226: {
            if (customerEncryption_ == null) {
              CustomerEncryption = new global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObjectData.Types.CustomerEncryption();
            }
            input.ReadMessage(CustomerEncryption);
            break;
          }
          case 232: {
            EventBasedHold = input.ReadBool();
            break;
          }
          case 802: {
            MediaLink = input.ReadString();
            break;
          }
          case 810: {
            SelfLink = input.ReadString();
            break;
          }
          case 818: {
            Kind = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the StorageObjectData message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Describes the customer-specified mechanism used to store the data at rest.
      /// </summary>
      public sealed partial class CustomerEncryption : pb::IMessage<CustomerEncryption>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<CustomerEncryption> _parser = new pb::MessageParser<CustomerEncryption>(() => new CustomerEncryption());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<CustomerEncryption> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Google.Events.Protobuf.Cloud.Storage.V1.StorageObjectData.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CustomerEncryption() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CustomerEncryption(CustomerEncryption other) : this() {
          encryptionAlgorithm_ = other.encryptionAlgorithm_;
          keySha256_ = other.keySha256_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CustomerEncryption Clone() {
          return new CustomerEncryption(this);
        }

        /// <summary>Field number for the "encryption_algorithm" field.</summary>
        public const int EncryptionAlgorithmFieldNumber = 1;
        private string encryptionAlgorithm_ = "";
        /// <summary>
        /// The encryption algorithm.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string EncryptionAlgorithm {
          get { return encryptionAlgorithm_; }
          set {
            encryptionAlgorithm_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "key_sha256" field.</summary>
        public const int KeySha256FieldNumber = 2;
        private string keySha256_ = "";
        /// <summary>
        /// SHA256 hash value of the encryption key.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string KeySha256 {
          get { return keySha256_; }
          set {
            keySha256_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as CustomerEncryption);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(CustomerEncryption other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (EncryptionAlgorithm != other.EncryptionAlgorithm) return false;
          if (KeySha256 != other.KeySha256) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (EncryptionAlgorithm.Length != 0) hash ^= EncryptionAlgorithm.GetHashCode();
          if (KeySha256.Length != 0) hash ^= KeySha256.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (EncryptionAlgorithm.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(EncryptionAlgorithm);
          }
          if (KeySha256.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(KeySha256);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (EncryptionAlgorithm.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(EncryptionAlgorithm);
          }
          if (KeySha256.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(KeySha256);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (EncryptionAlgorithm.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(EncryptionAlgorithm);
          }
          if (KeySha256.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(KeySha256);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(CustomerEncryption other) {
          if (other == null) {
            return;
          }
          if (other.EncryptionAlgorithm.Length != 0) {
            EncryptionAlgorithm = other.EncryptionAlgorithm;
          }
          if (other.KeySha256.Length != 0) {
            KeySha256 = other.KeySha256;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                EncryptionAlgorithm = input.ReadString();
                break;
              }
              case 18: {
                KeySha256 = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                EncryptionAlgorithm = input.ReadString();
                break;
              }
              case 18: {
                KeySha256 = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
